name: Sincronizar Catálogos
on:
  push:
    branches: [ main ]
    paths:
      - 'index.html'
  workflow_dispatch: # Esto te permite ejecutar el robot manualmente con un botón

jobs:
  sync-files:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Si un repo falla (ej. si aún no lo has creado), los demás se seguirán actualizando
      matrix:
        # AQUÍ VA EL FORMATO CORRECTO: Organizacion/Repositorio
        repo:
          - 'fv-forwarder-venture/celular'
          - 'fv-forwarder-venture/ninos'
          - 'fv-forwarder-venture/ropa-de-cama'
          - 'fv-forwarder-venture/sublimacion'
          - 'fv-forwarder-venture/papeleria-creativa'
          - 'fv-forwarder-venture/maquillaje'
    steps:
      - name: Descargar repositorio maestro
        uses: actions/checkout@v3

      - name: Copiar a repositorio destino
        run: |
          git config --global user.email "bot@forwarderventure.com"
          git config --global user.name "Bot Sincronizador FV"

          # 1. Clonar el repositorio destino
          git clone https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/${{ matrix.repo }}.git destino

          # 2. Copiar el index.html del Padre al Hijo
          cp index.html destino/index.html

          # 3. Entrar al Hijo, guardar cambios y subirlos
          cd destino
          git add index.html
          git commit -m "🚀 Auto-actualización de código maestro" || echo "Sin cambios"
          git push origin main
